import localFont from 'next/font/local'
import './globals.css'
import { ReduxProvider } from '@/lib/redux/provider'
import { ReactLenis } from 'lenis/react'
import { Alert, Snackbar } from '@mui/material'
import { NotistackProvider } from '@/components/common/Snackbar'

const Inter = localFont({
  src: './fonts/Inter.ttf',
  variable: '--font-geist-sans',
  weight: '100 200 300 400 500 600 700 800 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata = {
  title: 'Template',
  description: 'Generated by T1LKED'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${Inter.variable} ${Inter.className}`}>
        <NotistackProvider maxSnack={3} autoHideDuration={2000}>
          <ReactLenis root>
            <ReduxProvider>{children}</ReduxProvider>
          </ReactLenis>
        </NotistackProvider>
      </body>
    </html>
  )
}
